export const NAME_SUFFIXES = ['Jr.', 'Sr.', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'] as const;

/** Keep in sync with Campaign.Domain.Identity.ReservedUsernames. */
export const RESERVED_USERNAMES: ReadonlySet<string> = new Set([
  'admin',
  'administrator',
  'all',
  'alliance',
  'allies',
  'ally',
  'announcement',
  'anonymous',
  'anybody',
  'bot',
  'broadcast',
  'channel',
  'chat',
  'direct',
  'everyone',
  'faction',
  'game',
  'global',
  'group',
  'guest',
  'help',
  'here',
  'log',
  'mention',
  'mod',
  'moderator',
  'news',
  'none',
  'null',
  'official',
  'owner',
  'party',
  'player',
  'players',
  'private',
  'public',
  'root',
  'self',
  'server',
  'staff',
  'support',
  'system',
  'team',
  'unknown',
  'user',
  'users',
  'world',
  'you',
]);

export const REGISTER_FIELD_LABELS: Readonly<Record<string, string>> = {
  email: 'Email',
  username: 'Username',
  password: 'Password',
  confirmPassword: 'Confirm password',
  firstName: 'First name',
  middleInitial: 'Middle initial',
  lastName: 'Last name',
  suffix: 'Suffix',
  country: 'Country',
  region: 'State or province',
  city: 'City',
  timeZoneId: 'Time zone',
};

export const PROFILE_FIELD_LABELS: Readonly<Record<string, string>> = {
  username: 'Username',
  firstName: 'First name',
  middleInitial: 'Middle initial',
  lastName: 'Last name',
  suffix: 'Suffix',
  country: 'Country',
  region: 'State or province',
  city: 'City',
  timeZoneId: 'Time zone',
  preferredChatLanguage: 'Default chat language',
  currentPassword: 'Current password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
};
