import type { CampaignDetail } from './campaign.models';
import { GUEST_PREVIEW_CAMPAIGN_ID } from '../auth/guest-preview';

export function guestPreviewCampaign(): CampaignDetail {
  return {
    id: GUEST_PREVIEW_CAMPAIGN_ID,
    name: 'Guest preview',
    description: 'This map is only on this device. It is never saved to the server.',
    playerSlotCount: 8,
    occupiedPlayerSlots: 0,
    isPrivate: false,
    isPubliclyViewable: true,
    creatorIsParticipant: true,
    city: null,
    region: null,
    country: null,
    hasMap: false,
    assetTags: {},
    canManage: true,
    isParticipant: false,
    revision: 1,
    createdUtc: '2026-01-01T00:00:00+00:00',
    updatedUtc: '2026-01-01T00:00:00+00:00',
    factions: [],
    allyGroups: [],
    links: [],
    timeZoneId: 'UTC',
    startsAtLocal: '2099-01-01T12:00',
    startsUtc: '2099-01-01T12:00:00+00:00',
    endsUtc: '2099-03-01T12:00:00+00:00',
    roundCount: 8,
    roundLengthAmount: 1,
    roundLengthUnit: 'Weeks',
    phases: [
      { kind: 'Action', durationAmount: 3, durationUnit: 'Days' },
      { kind: 'Battle', durationAmount: 4, durationUnit: 'Days' },
    ],
    status: 'Scheduled',
    currentRound: null,
    currentPhaseNumber: null,
    currentPhaseKind: null,
    currentPhaseStartsUtc: null,
    currentPhaseEndsUtc: null,
    factionId: null,
    subfaction: null,
    canPlay: false,
    canChooseFaction: false,
    canChat: false,
    mentionableMembers: [],
    log: [],
    terrainTypes: [],
    structureTypes: [],
  };
}
